server:
  port: 8081
  security:
      enabled: false

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/passionchenjianye/config-server
          searchPaths: config